export default {
      home: '🏠',
      catalog: '📦',
      cart: '🛒',
      orders: '📋',
      profile: '👤',
      back: '⬅️',
      next: '➡️',
      ok: '✅',
      cancel: '❌',
      delete: '🗑️',
      edit: '✏️',
      refresh: '🔄',
      filter: '🔍',
      sort: '📊',
      info: 'ℹ️',
      warning: '⚠️',
      question: '❓',
      star: '⭐',
      heart: '❤️',
      fire: '🔥',
      clock: '⏰',
      calendar: '📅',
      location: '📍',
      phone: '📞',
      mail: '📧',
      link: '🔗',
      download: '📥',
      upload: '📤',
      lock: '🔒',
      unlock: '🔓',
      bell: '🔔',
      mute: '🔕'
    };